# Generated by Django 3.1.2 on 2020-10-19 22:49

from django.db import migrations, models
import storages.backends.gcloud


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=130)),
                ('caption', models.TextField(blank=True, max_length=2070)),
                ('file_local', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('file_cloud', models.FileField(storage=storages.backends.gcloud.GoogleCloudStorage, upload_to='uploads/%Y/%m/%d/')),
                ('instagram_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=130)),
                ('caption', models.TextField(blank=True, max_length=2070)),
                ('file_local', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('file_cloud', models.FileField(storage=storages.backends.gcloud.GoogleCloudStorage, upload_to='uploads/%Y/%m/%d/')),
                ('instagram_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
