# Generated by Django 3.1.2 on 2020-10-19 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='file_cloud',
        ),
        migrations.RemoveField(
            model_name='video',
            name='file_cloud',
        ),
        migrations.AlterField(
            model_name='image',
            name='file_local',
            field=models.FileField(upload_to='uploads/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='file_local',
            field=models.FileField(upload_to='uploads/%Y/%m/'),
        ),
    ]
