# Generated by Django 3.0.5 on 2020-11-16 04:10

import adminsortable.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_add_navbar_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='navbar',
            field=adminsortable.fields.SortableForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='gallery.Navbar'),
        ),
    ]
